name: Super-Linter

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read # to read your repository's code for linting
  statuses: write # to update the status checks for the linter results

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@487d0d80e66b54831132fe7b2095f9388a624462
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BIOME_FORMAT: false
          LINTER_RULES_PATH: .
