name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Install Neovim
        uses: rhysd/action-setup-vim@19e3dd31a84dbc2c5445d65e9b363f616cab96c1
        with:
          neovim: true
          version: v0.11.6 # renovate: datasource=github-releases depName=neovim/neovim
      - name: Setup Plenary
        run: |
          mkdir -p ~/.local/share/nvim/lazy
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/lazy/plenary.nvim
      - name: Run tests
        run: make test
